 
version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.8
      - image: postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    environment:
      - MIX_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: HEX_MIRROR=https://cdn.jsdelivr.net/hex mix local.hex --force
      - run: HEX_MIRROR=https://cdn.jsdelivr.net/hex mix local.rebar --force
      - run: HEX_MIRROR=https://cdn.jsdelivr.net/hex mix deps.get
      - run: mix compile --warnings-as-errors --force
      - run: mix test
      - store_test_results:
          path: /tmp/repo-example-test-results
      - run: mix credo
      - run: mix coveralls.json
      - run: bash <(curl -s https://codecov.io/bash)

        
