 
version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.8
    environment:
      - MIX_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      - run: HEX_MIRROR=https://cdn.jsdelivr.net/hex mix local.hex --force
      - run: HEX_MIRROR=https://cdn.jsdelivr.net/hex mix local.rebar --force
      - run: HEX_MIRROR=https://cdn.jsdelivr.net/hex mix deps.get
      - run: mix compile --warnings-as-errors --force
      - run: mix test
      - store_test_results:
          path: /tmp/repo-example-test-results
      - run: mix credo
      - run: mix coveralls.json
      - run: bash <(curl -s https://codecov.io/bash)

        
